FROM node:24.21.0-bookworm-slim AS build
WORKDIR /app
RUN npm install -g pnpm@10.32.1
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm db:generate && pnpm build
FROM nginx:1.28-alpine
COPY --from=build /app/dist/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
