import {useRef,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {Alert,Button,Image,Popconfirm,Select,Space,Spin} from "antd";
import {api} from "./api";
import {useCan,useUser} from "./shared";
import {editableSelectionCell,readableSelectionCell} from "./selection-protection";
import {prepareUpload,readUpload} from "./upload-file";
import {defaultImageConfig,fieldImages} from "./selection-field-types";
export function SelectionCustomPhoto(){
 const params=new URLSearchParams(location.search),id=params.get("id") || "",field=params.get("field") || "",name=params.get("fieldName") || "图片";
 let config={...defaultImageConfig};try{const input=JSON.parse(params.get("fieldConfig") || "{}");config={autoplay:input.autoplay!==false,colors:input.colors!==false,links:input.links!==false,upload:input.upload!==false,mobile:input.mobile!==false,max:Math.min(30,Math.max(1,Number(input.max) || 30))};}catch{}
 const user=useUser(); const canRead=useCan("selection.read"),canEdit=useCan("selection.manage");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[color,setColor]=useState("");const camera=useRef<HTMLInputElement>(null),album=useRef<HTMLInputElement>(null),lock=useRef(false);
 const data=useQuery({queryKey:["custom-photo",id,field],enabled:canRead && /^\d+$/.test(id),queryFn:()=>api("/style-selections/"+id),refetchInterval:busy?false:10000});
 const row=data.data?.data,images=fieldImages(row?.extraFields?.[field]),colors=String(row?.color || "").split("/").filter(Boolean);
 const run=async(action:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await action();}catch(error){setError((error as Error).message);}finally{await data.refetch();lock.current=false;setBusy(false);}};
 const upload=(files:File[])=>void run(async()=>{if(!canEdit || !row || !editableSelectionCell(row,field) || !config.mobile)throw Error("当前字段不允许手机上传");if(config.colors && !color)throw Error("请选择颜色");if(images.length+files.length>config.max)throw Error(`最多 ${config.max} 张图片`);for(const file of files){const prepared=await prepareUpload(file),uploaded=await api("/style-selections/images","POST",{data:await readUpload(prepared)});await api(`/style-selections/${id}/photos`,"POST",{action:"add",field,image:{id:crypto.randomUUID(),url:uploaded.data.url,color:config.colors?color:""}});}});
 if(!canRead)return <Alert type="error" title="需要选款登记查看权限"/>;
 if(!row)return <div className="mobile-photos">{data.error?<Alert type="error" title="无法读取本款图片，请重新扫码"/>:<Spin/>}</div>;
 return <main className="mobile-photos"><h2>{name} · 手机拍图</h2><p>序缇款号：{row.xutiStyleNo || "未填写"}　供应商款号：{row.supplierStyleNo || "未填写"}</p>{!readableSelectionCell(row,field) && <Alert type="info" title="图片内容受保护"/>}{String(row.claimedBy)===String(user.id) && <Button disabled={busy} onClick={()=>void run(async()=>{await api(`/style-selections/${id}/claim`,"POST",{action:"release"});})}>完成填表 / 释放</Button>}{error && <Alert type="error" title={error}/>}<p>已上传 {images.length} / {config.max} 张</p>{config.colors && <Select aria-label="拍图颜色" style={{width:"100%"}} value={color || undefined} placeholder="选择颜色" options={colors.map(value=>({value,label:value}))} onChange={setColor}/>}<div style={{display:"flex",flexWrap:"wrap",gap:10,marginBlock:12}}>{images.map(image=><div key={image.id} style={{width:120}}><Image src={image.url} width={120}/><p>{image.color}</p>{canEdit && editableSelectionCell(row,field) && <Popconfirm title="删除此图片？" onConfirm={()=>run(async()=>{await api(`/style-selections/${id}/photos`,"POST",{action:"remove",field,imageId:image.id});})}><Button disabled={busy}>删除</Button></Popconfirm>}</div>)}</div><Space wrap><Button disabled={!canEdit || !editableSelectionCell(row,field) || busy || !config.mobile} onClick={()=>camera.current?.click()}>拍照上传</Button>{config.upload && <Button disabled={!canEdit || !editableSelectionCell(row,field) || busy} onClick={()=>album.current?.click()}>相册选择</Button>}</Space><p>照片自动压缩至500KB以下，保存到本款的「{name}」字段。</p><input hidden ref={camera} type="file" capture="environment" accept="image/jpeg,image/png,image/webp" onChange={event=>{const files=Array.from(event.target.files || []);event.target.value="";upload(files);}}/><input hidden ref={album} multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const files=Array.from(event.target.files || []);event.target.value="";upload(files);}}/></main>;
}
