import {useState} from "react";
import {App,Button,Checkbox,Input,InputNumber,Modal,Popover,Select,Space,Tag,Tooltip} from "antd";
import {AppstoreOutlined,PlusOutlined,EyeOutlined,EyeInvisibleOutlined,EditOutlined,ArrowUpOutlined,ArrowDownOutlined} from "@ant-design/icons";
import {defaultTagConfig,orderedFieldTags,fieldValueError,defaultImageConfig,fieldTypes,type SelectionField,type FieldType} from "./selection-field-types";
export function SelectionFieldManager({columns,visible,canEdit,onSave,onVisible,onMove}:{columns:SelectionField[];visible:string[];canEdit:boolean;onSave:(field:SelectionField)=>boolean|void;onVisible:(key:string)=>void;onMove:(from:string,to:string)=>void}){
 const {message}=App.useApp();const [open,setOpen]=useState(false),[search,setSearch]=useState("");
 const [draft,setDraft]=useState<SelectionField|null>(null),[choices,setChoices]=useState("");
 const edit=(field?:SelectionField)=>{setOpen(false);setDraft(field?{...field,imageConfig:field.imageConfig || {...defaultImageConfig,colors:field.key!=="labelImages"}}:{key:"custom:"+crypto.randomUUID(),label:"",width:180,custom:true,type:"text"});setChoices(field?.options?.join("\n") || "");};
 const save=()=>{if(!draft)return;const label=draft.label.trim();if(!label)return void message.error("请填写字段名称");if(columns.some(field=>field.key!==draft.key && field.label===label))return void message.error("字段名称已存在");const options=[...new Set(choices.split("\n").map(value=>value.trim()).filter(Boolean))];if(["single","multiple"].includes(draft.type || "") && (!options.length || options.length>100 || options.some(value=>value.includes("/") || value.length>80)))return void message.error("请填写1至100个选项，每行一个，最多80字且不能含 / ");if(draft.type==="tags" && (options.length>100 || options.some(value=>value.includes("/") || value.length>80) || (!({...defaultTagConfig,...draft.tagConfig}).allowCustom && !options.length)))return void message.error("请填写有效候选标签，每行一个，最多100项，每项最多80字且不含 / ");if(onSave({...draft,label,options})!==false)setDraft(null);};
 return <><Popover trigger="click" open={open} onOpenChange={setOpen} placement="bottomLeft" content={<div className="selection-field-manager"><Input.Search aria-label="搜索字段" placeholder="搜索字段" value={search} onChange={event=>setSearch(event.target.value)}/><div className="selection-field-list">{columns.filter(field=>field.label.includes(search)).map(field=>{const index=columns.indexOf(field);return <div key={field.key}><span className="selection-field-title">{field.label}<Tag>{field.custom?fieldTypes[field.type || "text"]:"内置"}</Tag></span><Space size={0}><Tooltip title="上移"><Button size="small" type="text" disabled={!index} icon={<ArrowUpOutlined/>} onClick={()=>onMove(field.key,columns[index-1].key)}/></Tooltip><Tooltip title="下移"><Button size="small" type="text" disabled={index===columns.length-1} icon={<ArrowDownOutlined/>} onClick={()=>onMove(field.key,columns[index+1].key)}/></Tooltip><Button size="small" type="text" aria-label={"编辑字段"+field.label} icon={<EditOutlined/>} disabled={!canEdit} onClick={()=>edit(field)}/><Button size="small" type="text" aria-label={(visible.includes(field.key)?"隐藏":"显示")+field.label} icon={visible.includes(field.key)?<EyeOutlined/>:<EyeInvisibleOutlined/>} onClick={()=>onVisible(field.key)}/></Space></div>;})}</div><Button block type="dashed" icon={<PlusOutlined/>} disabled={!canEdit} onClick={()=>edit()}>添加字段</Button></div>}><Button type="text" icon={<AppstoreOutlined/>}>字段管理</Button></Popover>
 <Modal title={columns.some(field=>field.key===draft?.key)?"编辑字段":"添加字段"} open={!!draft} onCancel={()=>setDraft(null)} onOk={save} okText="保存" cancelText="取消">{draft && <div className="selection-field-form"><label>字段名称<Input aria-label="字段名称" maxLength={40} value={draft.label} onChange={event=>setDraft({...draft,label:event.target.value})}/></label>{draft.custom?<label>字段类型<Select aria-label="字段类型" showSearch optionFilterProp="label" value={draft.type || "text"} options={Object.entries(fieldTypes).map(([value,label])=>({value,label}))} onChange={(type:FieldType)=>setDraft({...draft,type})}/></label>:<p>内置字段保留原有业务类型。</p>}{["single","multiple","tags"].includes(draft.type || "") && <label>选项（每行一个）<Input.TextArea aria-label="字段选项" rows={5} value={choices} onChange={event=>setChoices(event.target.value)}/></label>}{draft.type==="tags" && <div><h4>标签功能设置</h4><Checkbox checked={{...defaultTagConfig,...draft.tagConfig}.allowCustom} onChange={event=>setDraft({...draft,tagConfig:{...defaultTagConfig,...draft.tagConfig,allowCustom:event.target.checked}})}>允许输入新标签</Checkbox><Checkbox checked={{...defaultTagConfig,...draft.tagConfig}.multiple} onChange={event=>setDraft({...draft,tagConfig:{...defaultTagConfig,...draft.tagConfig,multiple:event.target.checked}})}>允许多选</Checkbox><label>标签数量上限<InputNumber min={1} max={100} precision={0} disabled={!({...defaultTagConfig,...draft.tagConfig}).multiple} value={draft.tagConfig?.max || 30} onChange={value=>setDraft({...draft,tagConfig:{...defaultTagConfig,...draft.tagConfig,max:value || 30}})}/></label><label>显示顺序<Select value={draft.tagConfig?.order || "selection"} options={[{value:"selection",label:"选择顺序"},{value:"options",label:"候选标签顺序"},{value:"alphabetical",label:"名称排序"}]} onChange={order=>setDraft({...draft,tagConfig:{...defaultTagConfig,...draft.tagConfig,order}})}/></label><label>标签颜色<Select value={draft.tagConfig?.color || "orange"} options={["orange","blue","green","purple","red","default"].map((value,index)=>({value,label:["橙色","蓝色","绿色","紫色","红色","默认"][index]}))} onChange={color=>setDraft({...draft,tagConfig:{...defaultTagConfig,...draft.tagConfig,color}})}/></label></div>}{(draft.type==="image" || ["images","labelImages"].includes(draft.key)) && <div><h4>图片功能设置</h4>{(["colors","links","upload","mobile"] as const).map((key,index)=><div key={key}><Checkbox disabled={key==="colors" && draft.key==="labelImages"} checked={{...defaultImageConfig,...draft.imageConfig}[key]} onChange={event=>setDraft({...draft,imageConfig:{...defaultImageConfig,...draft.imageConfig,[key]:event.target.checked}})}>{["按颜色标记","允许图片链接","允许上传和粘贴图片","允许手机扫码拍图"][index]}</Checkbox></div>)}<label>图片数量上限<InputNumber min={1} max={30} precision={0} value={draft.imageConfig?.max || 30} onChange={value=>setDraft({...draft,imageConfig:{...defaultImageConfig,...draft.imageConfig,max:value || 30}})}/></label></div>}<p>字段设置保存在当前浏览器。隐藏字段保留原有数据；修改类型不转换或清除原值，不兼容内容需修正后保存。</p></div>}</Modal></>;
}
export function SelectionFieldInput({field,value,disabled,onChange}:{field:SelectionField;value:string;disabled:boolean;onChange:(value:string)=>void}){
 const {message}=App.useApp();
 const type=field.type || "text";
 if(type==="tags"){
  const config={...defaultTagConfig,...field.tagConfig};
  return <Select aria-label={field.label} style={{width:"100%"}} disabled={disabled} allowClear mode={config.allowCustom?"tags":"multiple"} tokenSeparators={config.allowCustom?["/"]:undefined} value={orderedFieldTags(field,value)} placeholder="输入或选择标签" options={(field.options || []).map(tag=>({value:tag,label:tag}))} onChange={values=>{const next=orderedFieldTags(field,values.join("/")).join("/");const error=fieldValueError(field,next);if(error){message.warning(error);return;}onChange(next);}}/>;
 }
 if(type==="checkbox")return <input aria-label={field.label} type="checkbox" disabled={disabled} checked={value==="true"} onChange={event=>onChange(String(event.target.checked))}/>;
 if(type==="single" || type==="multiple")return <Select aria-label={field.label} style={{width:"100%"}} disabled={disabled} allowClear mode={type==="multiple"?"multiple":undefined} value={type==="multiple"?(value?value.split("/"):[]):value || undefined} options={(field.options || []).map(item=>({value:item,label:item}))} onChange={next=>onChange(Array.isArray(next)?next.join("/"):next || "")}/>;
 if(type==="date")return <Input aria-label={field.label} type="date" disabled={disabled} value={value} onChange={event=>onChange(event.target.value)}/>;
 if(["number","currency","percent"].includes(type))return <Input aria-label={field.label} inputMode="decimal" disabled={disabled} prefix={type==="currency"?"¥":undefined} suffix={type==="percent"?"%":undefined} value={value} onChange={event=>onChange(event.target.value)}/>;
 if(type==="link")return <Space.Compact style={{width:"100%"}}><Input aria-label={field.label} disabled={disabled} maxLength={2000} placeholder="https://" value={value} onChange={event=>onChange(event.target.value)}/>{/^https?:\/\//i.test(value) && <Button href={value} target="_blank" rel="noopener noreferrer">打开</Button>}</Space.Compact>;
 return <Input.TextArea aria-label={field.label} disabled={disabled} maxLength={2000} autoSize={{minRows:1,maxRows:3}} placeholder="" value={value} onChange={event=>onChange(event.target.value)}/>;
}
